#!/bin/bash
#$ -pe mpich_single 3
#$ -N myjob
#$ -cwd
#$ -j y
#$ -S /bin/bash
MYPROG="./HIS"
MPICH2_ROOT="/opt/mpich2/gnu"
NSLOTS=3

#cat /proc/cpuinfo
nvidia-smi
cat $TMPDIR/machines
export LD_LIBRARY_PATH=/share/apps/amd-opencl/AMDAPPSDK-3.0/lib/x86_64/sdk:$LD_LIBRARY_PATH

#50X50X3200

/usr/bin/time $MPICH2_ROOT/bin/mpiexec -machinefile machinefile_3_maquinas -n $NSLOTS $MYPROG 50 50 3200
#/usr/bin/time $MPICH2_ROOT/bin/mpiexec -machinefile machinefile_3_maquinas -n $NSLOTS $MYPROG 200 200 200

exit 0

