#!/bin/bash
#$ -pe mpich_single 256
#$ -N myjob
#$ -cwd
#$ -j y
#$ -S /bin/bash
MYPROG="./HIS"
MPICH2_ROOT="/opt/mpich2/gnu"
echo "NHOSTS=$NHOSTS, NSLOTS=$NSLOTS, TMPDIR/machines=$TMPDIR/machines"
cat $TMPDIR/machines
sort $TMPDIR/machines | uniq > $TMPDIR/machines2
cat $TMPDIR/machines2
export LD_LIBRARY_PATH=/share/apps/amd-opencl/AMDAPPSDK-3.0/lib/x86_64/sdk:$LD_LIBRARY_PATH

#50X50X3200

/usr/bin/time $MPICH2_ROOT/bin/mpiexec -machinefile $TMPDIR/machines2 -n 8 $MYPROG 50 50 3200
/usr/bin/time $MPICH2_ROOT/bin/mpiexec -machinefile $TMPDIR/machines2 -n 8 $MYPROG 50 50 3200
/usr/bin/time $MPICH2_ROOT/bin/mpiexec -machinefile $TMPDIR/machines2 -n 8 $MYPROG 50 50 3200

#200X200X200

#/usr/bin/time $MPICH2_ROOT/bin/mpiexec -machinefile $TMPDIR/machines -n $NSLOTS $MYPROG 200 200 200
#/usr/bin/time $MPICH2_ROOT/bin/mpiexec -machinefile $TMPDIR/machines -n $NSLOTS $MYPROG 200 200 200
#/usr/bin/time $MPICH2_ROOT/bin/mpiexec -machinefile $TMPDIR/machines -n $NSLOTS $MYPROG 200 200 200


exit 0

